apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rush
  namespace: rush
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: rush.example.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: rush-api
                port:
                  number: 3001
          - path: /me
            pathType: Prefix
            backend:
              service:
                name: rush-api
                port:
                  number: 3001
          - path: /gems
            pathType: Prefix
            backend:
              service:
                name: rush-api
                port:
                  number: 3001
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: rush-api
                port:
                  number: 3001
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: rush-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rush-web
                port:
                  number: 80
